server {
    listen      443 ssl;
    include     ssl/self-signed.conf;
    include     ssl/ssl-params.conf;

    location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header   Host             $host;
            proxy_set_header   Connection       $http_connection;
            proxy_set_header   X-Scheme         $scheme;
    }
}

server {
    listen 80;
    return 301 https://$host$request_uri;
}
